# Site
name: "Muda Islami"
title: "Muda Islami"
description: "Kebetulan menemukan halaman ini? Tidak, semua sudah bagian dari rencana-Nya!"
logo: 'assets/images/logo.webp'
favicon: 'assets/images/logo.webp'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'mudaislami'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: islamimuda@gmail.com

# Authors
authors:
  mudaislami:
    name: '@mudaislami'
    display_name: '@mudaislami'
    gravatar: 52374c578ca1507feebeedd19fab7ae6
    email: islamimuda@gmail.com
    web: https://instagram.com/mudaislami/
    twitter: #
    description: "Penulis di Muda Islami"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
# highlighter: none
rouge: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
